version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: codeva_postgres
    environment:
      POSTGRES_DB: codeva_fullstack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - codeva_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: codeva_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - codeva_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Backend API
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: codeva_api
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/codeva_fullstack
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - codeva_network
    restart: unless-stopped
    volumes:
      - ./server/uploads:/app/uploads

  # Frontend React App
  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: codeva_web
    environment:
      VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - codeva_network
    restart: unless-stopped

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    container_name: codeva_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
      - api
    networks:
      - codeva_network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  codeva_network:
    driver: bridge
